### ISSUE TITLE
:idoc can not open .c files?

### ISSUE THREAD

**Issue by monouser7dig** [terrychou/iVim#35]
using :idoc files picker, most file formats are greyed out and can thus not be opened.
Is there a workaround/ is it an iOS restriction?

thanks

**Comment by terrychou** [comment]
iVim should open most types of files. Plain text files (like .c) are supported well.

It may be caused by the original app (from where you are trying to pick the files) sometimes. You may try them in the Files app first. Or you may try and reboot your device.

**Comment by monouser7dig** [comment]
The issue appeared in google-drive, it works using iCloudDrive indeed.

**Comment by sedm0784** [comment]
I believe this is a bug in Google Drive.

I had to work around a similar issue with Google Drive in an app I develop by using a `public.data` UTI to allow the opening of *all* files instead of the more specific (correct) ones I was using prevoiusly.

**Comment by monouser7dig** [comment]
that list has all sorts of type identifiers like `public.c-source` as well, which are in that [iVim plist](https://github.com/terrychou/iVim/blob/621922751afbe6534f77d6d2e3281595a04ced26/iVim/Info.plist#L258) but that is just guess work at best from my side

**Comment by sedm0784** [comment]
@monouser7dig The file types listed in `UTExportedTypeDeclarations` in the Info.plist aren't the ones used for declaring which types to enable in the Document picker. (Unless I'm misremembering how this works,) [this line](https://github.com/terrychou/iVim/blob/621922751afbe6534f77d6d2e3281595a04ced26/iVim/VimViewController%2BUIDocumentPickerDelegate.swift#L13) is the one where those types are specified.

**Comment by monouser7dig** [comment]
so maybe all the other .c-source and shell and so on would help if they were added?

**Comment by sedm0784** [comment]
No, they should all be covered by the single `public.data` UTI already specified. See the documentation for [conformance](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-BCGJGJGA) for the gory details.

My hunch (based on prior experience) is that Google Drive is somehow declaring the file to actually be something other than a `public.c-source` file. It's only a hunch though, because I don't know by what mechanism they could be specifying this, and indeed what other UTI they could be declaring that file to be that *doesn't* conform to the existing `public.data` UTI in the code.

Perhaps someone with more experience in this area (because I'm pretty sure the answer doesn't lie in the documentation) will chime in with a definitive answer of what is really happening and whether it's something iVim can workaround.

**Comment by monouser7dig** [comment]
>  See the documentation for conformance for the gory details.

yes I see, suspected something like this to be the case

>  I'm pretty sure the answer doesn't lie in the documentation) will chime in with a definitive answer of what is really happening and whether it's something iVim can workaround.

solid access to source code files would certainly be a win (or vin) 😄

**Comment by eigoninaritai-naokichi** [comment]
I can’t open .kt(kotlin source) in iCloud.
Do you have any sugesstions?

**Comment by terrychou** [comment]
Yes, files behave weirdly in iCloud Drive.
This will be fixed in update.

**Comment by eigoninaritai-naokichi** [comment]
Thanks for replying.
I am looking forward to be updated it.

**Comment by terrychou** [comment]
Is this problem solved in the latest update?

**Comment by monouser7dig** [comment]
it's not fixed for google drive at least, but maybe that was expected

**Comment by eigoninaritai-naokichi** [comment]
It’s fixes for iCloud drive at least.
Thanks for fixing!
